#!/bin/bash

ME="${0##*/}"

function cover() {
    # cargo install cargo-tarpaulin
    
    cargo tarpaulin -o html
    echo "coverage report saved to tarpaulin-report.html"
}

# tags repo with specified tag
function tag() {
  git tag -a "$1" -m "$2"
  git push origin "$1"
}

function usage {
  echo "usage: $ME cover                       # generates coverage report"
  echo "       $ME tag <version> <description> # tags branch with the specified version"
}

case $1 in
  cover)        cover "${@:2}";;
  tag)          tag "${@:2}";;
  *)            usage;;    
esac
