use super::*;

/// Round-trip the `PartialEq<str>` / `PartialEq<&str>` impls in both
/// directions for a string-newtype generated by `impl_str_partial_eq!`.
macro_rules! str_eq_round_trip {
    ($name:ident, $t:ty, $matches:expr, $differs:expr) => {
        #[test]
        fn $name() {
            let v = <$t>::from($matches);

            assert_eq!(v, *$matches);
            assert_eq!(v, $matches);
            assert_eq!(*$matches, v);
            assert_eq!($matches, v);

            assert_ne!(v, $differs);
            assert_ne!($differs, v);
        }
    };
}

str_eq_round_trip!(symbol_partial_eq_str_round_trip, Symbol, "AAPL", "MSFT");
str_eq_round_trip!(exchange_partial_eq_str_round_trip, Exchange, "NASDAQ", "NYSE");
str_eq_round_trip!(currency_partial_eq_str_round_trip, Currency, "USD", "EUR");
